<div class="content">
    <h1>IMI - Monitoring System </h1>

</div>

<p>Icinga web 2 module imi_war_room </p><br>
    ================================= <br>

    This module adds four tabs into Icinga web 2. Each tab has a different dashboard:<br>

    Tab 1: Down hosts - lists red boxes with the host names that are down. If a new host shows up,<br>
    the box starts to blink and a sound "Host is down" is heard, until it is acknowledged.<br>

    Tab 2: Warnings - lists orange boxes with the host name and his services that are in a 'warning' state.<br>
    If a new service shows up, the box starts to blink and a sound "Warning" is heard,<br>
    until it is acknowledged.<br>

    Tab 3: Critical - lists light red boxes with the host name and his services that are in a 'critical' state.<br>
    If a new service shows up, the box starts to blink and a sound "Critical service" is heard,<br>
    until it is acknowledged.<br>

    Tab 3: Critical and Warnings - lists blue boxes with the host name and the number of critical and warning services.<br>

    Installation<br>
    -------------<br>
    Linux:<br>
    Add the module into /usr/share/icingaweb2/modules<br>

    About Us<br>
    =================<br>

    [iMi digital GmbH](http://www.imi.de/) offers Contao related open source modules. If you are confronted with any bugs, you may want to open an issue here.<br>

    In need of support or an implementation of a modul in an existing system, [free to contact us](mailto:digital@iMi.de). In this case, we will provide full service support for a fee.<br>

    Of course we provide development of closed-source moduls as well.<br>


    Icinga web 2 module imi_war_room <br>
    ================================= <br>
    Dieses Modul fügt vier etikette in das Icinga web 2. Jede etikette bietet eine andere Ansicht:<br>

    Tab 1: Down hosts - listet rote Boxen mit dem Hostnamen der nicht erreichbar ist. Wenn ein neuer Host erscheint,<br>
    dann fängt die Box an zu blinken und ein Geräusch "Host is down" ist hörbar, solange das Problem<br>
    nicht anerkannt wird.

    Tab 2: Warnings - listet orange Boxen mit dem Hostnamen und seiner Dienste die sich im 'warnung' Zustand befinden.<br>
    Wenn ein neuer Dienst erscheint, dann fängt die Box an zu blinken und ein Geräusch "Warning" ist hörbar, solange das Problem nicht anerkannt wird.<br>


    Tab 3: Critical - listet hell rote Boxen mit dem Hostnamen und seiner Dienste die sich im 'kritischem' Zustand befinden.<br>
    Wenn ein neuer Dienst erscheint, dann fängt die Box an zu blinken und ein Geräusch "Critical service"<br>
    ist hörbar, solange das Problem nicht anerkannt wird.<br>

    Tab 3: Critical  and Warnings - lists blue boxes with the host name and the number of critical and warning services.<br>

    Installation<br>
    -------------<br>
    Linux:<br>
    Füge das Modul unter dem Pfad hinzu:  /usr/share/icingaweb2/modules<br>

    Bekannte Probleme<br>
    -----------------<br>

    siehe oben (Englisch)<br>

    Über iMi digital<br>
    ================<br>

    [iMi digital GmbH](http://www.imi.de/) bietet eine breite Auswahl an verschiedenen Open-Source-Module für Contao an. Beim Auftreten von Fragen oder Bugs kann hier sehr gerne ein Thread geöffnet werden.<br>

    [Kontaktieren Sie uns](mailto:digital@iMi.de) gerne, wenn Sie Support für die Implementierung eines Moduls in ein bereits bestehendes Shop-System benötigen.In diesem Fall bieten wir einen kostenpflichtigen Full-Service-Support an.<br>


<blockquote> @autor Natasza Szczypien, Alexander Menk, Stephan Nachtsheim</blockquote>

