<!-- * Autor:  Natasza Szczypien, Alexander Menk, Stephan Nachtsheim
     * Shows the current Host with services that have a warning.
     * If there is a new warning, than a sound "New service warning" is playing.
-->



<div id="warning-header">
    <h1 id="warning-header-text">Warnings</h1>
    <span id="warning-header-span-nr">
           <h1 id="warning-header-nr" class="orange"><?= $this->warningsSummary ?></h1>

    </span>
</div>
<hr>

<?php
if ($this->warningSignal === true) {
    echo $this->render('/sound/warning.phtml');
     }
?>

<?php
//TODO: for each host list warnings
if ($this->noWarnings === true) {
    echo " No Warnings. ";
} else {
    foreach ($this->objects as $host) { ?>

        <div class="warning-icon orange">
            <div class="c-div-host-name">
                <h2><?php echo $host['hostname']; ?></h2>
            </div>
            <?php foreach ($host['services'] as $service) {
                if ($service->service_acknowledged) { ?>
                    <div class="c-div-service-name">
                        <h2><?php echo $service->service_display_name; ?></h2>
                    </div>
                <?php } else { ?>
                    <div class="c-div-service-name blink_me">
                        <h2><?php echo $service->service_display_name; ?></h2>
                    </div>
                <?php } // end else?>

            <?php } // end inner for each ?>
        </div> <!-- end critical icon -->
    <?php } // end outer for each?>
<?php } //end else?>


<style>
    .blink_me {
        animation: blinker 4s linear infinite;
    }

    @keyframes blinker {
        50% { opacity: 0.0; }
    }
</style>