<!-- * Autor: Natasza Szczypien, Alexander Menk, Stephan Nachtsheim
     * Shows the current down Hosts, if a host is not acknowledged than
     * the host-box blinks and you can here a sound "Host is down".
-->

<?php
if ($this->downSignal === true) {
    echo $this->render('/sound/hostIsDown.phtml');
}
?>

<div id="down-header">
    <h1 id="down-header-text">Down hosts</h1>
    <span id="down-header-span-nr">
           <h1 id="down-header-nr" class="red"><?= "" . $this->downNumber ?></h1>
    </span>
</div>
<hr>

<!-- CONTENT -->
<?php
if ($this->hostsUp === true) {
    echo " All Hosts are UP";
} else {
    /* Displays the blocks with host names*/
foreach($this->downHostList as $host) { ?>
    <div class="down-icon">
        <?php if($host->host_acknowledged){ ?>
            <div class="div-host-name">
                <h2 id="host-name"><?php echo $host->host_display_name; ?></h2>
            </div>
       <?php } else { ?>
            <!-- If a Host is not acknowledged it blinks -->
            <div class="div-host-name blink_me">
                <h2 ><?php echo $host->host_display_name; ?></h2>
            </div>
        <?php } ?>
    </div>
<?php } }?>


<style>
    .blink_me {
        animation: blinker 4s linear infinite;
    }

    @keyframes blinker {
        50% { opacity: 0.0; }
    }
</style>
