<!-- * Autor:  Natasza Szczypien, Alexander Menk, Stephan Nachtsheim
     * Shows the current Host with services that have a critical state.
     * If there is a new sritical service, than a sound "Critical service" is playing.
-->

<div id="critical-header">
    <h1 id="critical-header-text">Critical services</h1>
    <span id="critical-header-span-nr">
           <h1 id="critical-header-nr" class="red"><?= $this->criticalsSummary ?></h1>

    </span>
</div>
<hr>
<?php
if ($this->criticalSignal === true) {
    echo $this->render('/sound/criticalService.phtml');
} ?>

<?php

if ($this->noCriticals === true) {
    echo " No critical services. ";
} else {
foreach ($this->objects as $host) { ?>

<div class="critical-icon red">
    <div class="c-div-host-name">
        <h2><?php echo $host['hostname']; ?></h2>
    </div>
    <?php foreach ($host['services'] as $service) {
        if ($service->service_acknowledged) { ?>
            <div class="c-div-service-name">
                <h2><?php echo $service->service_display_name; ?></h2>
            </div>
        <?php } else { ?>
            <div class="c-div-service-name blink_me">
                <h2><?php echo $service->service_display_name; ?></h2>
            </div>
        <?php } // end else?>

    <?php } // end inner for each ?>
</div> <!-- end critical icon -->
<?php } // end outer for each?>
<?php } //end else?>



<style>
    .blink_me {
        animation: blinker 4s linear infinite;
    }

    @keyframes blinker {
        50% { opacity: 0.0; }
    }
</style>

